const commonFacts = [
    "British Columbia is the third largest province in Canada.",
    "British Columbia has 20 rivers.",
    "The tallest mountain in British Columbia is Mount Logan.",
    "The national animal of British Columbia is the Kermode Bear.",
    "British Columbia is a top fruit producer of cranberries and blueberries.",
    "The longest river in British Columbia is the Fraser River.",
    "BC has a coastal line stretches 25 725 kilometers.",
    "BC has 1031 provincial parks.",
    "There are more than 200 Indigenous groups in British Columbia.",
    "British Columbia’s population is about 5 million.",
    "British Columbia covers 9.5% of Canada’s area.",
    "British Columbia borders the Pacific Ocean.",
    "The US state that borders British Columbia from the north is Alaska.",
    "From north to south, British Columbia is 1200 kilometers long.",
    "There are 40 000 islands in British Columbia.",
    "British Columbia has 34 Indigenous languages.",
    "British Columbia is so big, it actually has 2 different time zones.",
    "The most popular whale in British Columbia is the humpback whale.",
    "British Columbia has this animal called the common loon, which is on the one dollar coin.",
    "The lodgepole pine is the most common tree in British Columbia.",
    "British Columbia is covered in 262 130 kilometers squared of forest.",
    "British Columbia is home to the only grizzly bear sanctuary in Canada.",
    "There are 3500 cougars in British Columbia.",
    "The warmest freshwater lake in Canada is the Osoyoos Lake.",
    "The largest island in British Columbia is Vancouver Island.",
]
export default commonFacts